### ISSUE TITLE
Race condition between SetPrompt and ioloop

### ISSUE THREAD

**Issue by knz** [chzyer/readline#79]
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=20052#334279584_2_20052_problem:

```
 github.com/chzyer/readline.(*RuneBuffer).PromptLen()
      /go/src/github.com/chzyer/readline/runebuf.go:78 +0x5c

vs.

 github.com/cockroachdb/cockroach/cli.runInteractive()  // where SetPrompt() is called
     /go/src/github.com/cockroachdb/cockroach/cli/sql.go:283 +0x2b9
```

The SetPrompt method should protect the prompt variable with a mutex.

**Comment by chzyer** [comment]
@knz Thanks! It's fixed now.

**Comment by knz** [comment]
Hum I'm sorry but no it's not fixed. `promptLen` is not protected by the mutex. Look at the original trace:
```
Write at 0x00c42043c5a0 by goroutine 19:
  github.com/chzyer/readline.(*RuneBuffer).SetPrompt()
      /mnt/kena/go/src/github.com/chzyer/readline/runebuf.go:503 +0xa0
  github.com/chzyer/readline.(*Operation).SetPrompt()
      /mnt/kena/go/src/github.com/chzyer/readline/operation.go:87 +0x62
  github.com/chzyer/readline.(*Instance).SetPrompt()
      /mnt/kena/go/src/github.com/chzyer/readline/readline.go:168 +0x62
  github.com/cockroachdb/cockroach/cli.runInteractive()
      /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql.go:286 +0x234
  github.com/cockroachdb/cockroach/cli.TestSQLLex.func2()
      /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql_test.go:117 +0x61
  github.com/cockroachdb/cockroach/cli.captureOutput()
      /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:164 +0x1bc
  github.com/cockroachdb/cockroach/cli.TestSQLLex()
      /mnt/kena/go/src/github.com/cockroachdb/cockroach/cli/sql_test.go:121 +0x5f6
  testing.tRunner()
      /mnt/kena/go1.7rc5/src/testing/testing.go:610 +0xc9

Previous read at 0x00c42043c5a0 by goroutine 133:
  github.com/chzyer/readline.(*RuneBuffer).promptLen()
      /mnt/kena/go/src/github.com/chzyer/readline/runebuf.go:85 +0x5c
  github.com/chzyer/readline.(*RuneBuffer).getSplitByLine()
      /mnt/kena/go/src/github.com/chzyer/readline/runebuf.go:381 +0x3c
  github.com/chzyer/readline.(*RuneBuffer).IdxLine()
      /mnt/kena/go/src/github.com/chzyer/readline/runebuf.go:388 +0xaa
  github.com/chzyer/readline.(*RuneBuffer).Clean()
      /mnt/kena/go/src/github.com/chzyer/readline/runebuf.go:530 +0x53
  github.com/chzyer/readline.(*Operation).ioloop()
      /mnt/kena/go/src/github.com/chzyer/readline/operation.go:101 +0x3286
```

As you can see the race is with `IdxLine` which uses .... `promptLen` which is not protected.

**Comment by chzyer** [comment]
Yes, you are right.
What's command you run to detect race condition?
I have try `go test -race -run=TestMain` in corkroachdb before, but it's passed.

**Comment by knz** [comment]
`make testrace PKG=./cli TESTS=TestSQLLex`

Run this from the branch `fix-sql-comment` from https://github.com/knz/cockroach though.

**Comment by chzyer** [comment]
@knz 
It should fixed now. :) Sorry for the later fix.
